backend/home/urls.py
from django.urls import path
from home import views

urlpatterns = [
    path('', views.homePage, name='home'),
    path('search/', views.searchPage, name='search'),
]

backend/jetsetradio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('artists/', include('artist.urls')),
    path('genre/', include('genre.urls')),
    path('songs/', include('music.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name='registration/reset_password.html'),
        name='reset_password'),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/reset_password_sent.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='registration/reset.html'), name=(
                 'password_reset_confirm')),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='registration/reset_password_complite.html'), name=(
                 'password_reset_complete')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/music/urls.py
from django.urls import path
from music import views

urlpatterns = [
    path('', views.songsPage, name='songs'),
    path('<slug>-ID-<pk>/', views.singleSongPage, name='single-song'),
    path('download/<int:track_id>/', views.downloadTrack,
         name='download-track'),
    path('create/', views.songCreateAndEdit, name='song-create'),
    path('edit/<slug>-ID-<pk>/', views.songCreateAndEdit, name='song-edit'),
    path('delete/<slug>-ID-<pk>/', views.songDelete, name='song-delete')
]

backend/music/models.py
from django.db import models
from django.contrib.auth import get_user_model
from users.models import Comment
from genre.models import Genre

User = get_user_model()


class Music(models.Model):
    '''Music model'''
    title = models.CharField(max_length=256)
    thumbnail = models.ImageField(upload_to='SongsThumbnails/',
                                  default='SongsThumbnails/default.jpg')
    artist = models.ForeignKey(User, on_delete=models.CASCADE)
    genres = models.ManyToManyField(Genre)
    song = models.FileField(upload_to='Songs/')
    song_duration = models.CharField(max_length=200, null=True, blank=True)
    lyrics = models.TextField(null=True)
    slug = models.SlugField(null=True, blank=True)
    published = models.BooleanField(default=False)
    page_view = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Music'
        verbose_name_plural = 'Music'

    def __str__(self):
        return self.title


class MusicComment(Comment):
    '''Music comment model'''
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    music = models.ForeignKey(Music, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Commnets'

    def comment_title(self):
        return (f'Comment on {self.music} by '
                f'{(self.owner.username if self.owner.username
                    else self.owner.email)}')

backend/users/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import (AbstractBaseUser,
                                        BaseUserManager, PermissionsMixin)


class CustomUserManager(BaseUserManager):
    '''Custom user manager'''
    def create_user(self, email, password=None, **extra_fields):
        '''Creates and saves a user using email address'''
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password):
        '''Creates and saves a new super user using email address'''
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    '''Custom user model that support using email instead of username'''
    email = models.EmailField(max_length=255, unique=True)
    username = models.CharField(max_length=32, unique=True)
    picture = models.ImageField(upload_to='ArtistsPictures/',
                                default='ArtistsPictures/default.jpg')
    slug = models.SlugField()
    bio = models.TextField(max_length=1024)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.username)
        if not self.username:
            self.username = 'user' + str(len(CustomUser.objects.all()))
        super().save(*args, **kwargs)


class Comment(models.Model):
    body = models.TextField(max_length=320)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

backend/music/forms.py
from django.forms import ModelForm, SelectMultiple, FileInput
from users.forms import CommentForm
from music.models import MusicComment, Music


class MusicCreateForm(ModelForm):
    class Meta:
        model = Music
        fields = ['title', 'thumbnail', 'genres', 'song', 'lyrics']
        widgets = {
            'genres': SelectMultiple(attrs={'class': 'cart__amount'}),
            'thumbnail': FileInput(attrs={'type': 'file',
                                          'name': 'thum bnail',
                                          'accept': 'image/*',
                                          'class': 'form-control',
                                          'id': 'id_thumbnail', }),
            'song': FileInput(attrs={'type': 'file',
                                     'name': 'song',
                                     'accept': 'audio/*',
                                     'class': 'form-control',
                                     'id': 'id_song', })
        }

    def __init__(self, *args, **kwargs):
        super(MusicCreateForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs.update({'class': 'sign__input'})
        self.fields['thumbnail'].widget.attrs.update({'class': 'cart__amount'})
        self.fields['song'].widget.attrs.update({'class': 'cart__amount'})
        self.fields['lyrics'].widget.attrs.update({'class': 'sign__textarea'})


class MusicCommentForm(CommentForm):
    class Meta:
        model = MusicComment
        fields = ['body']

        labels = {
            'body': 'Add a comment'
        }

backend/music/views.py
import os
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import FileResponse, HttpResponseNotFound
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from music.models import Music
from music.forms import MusicCommentForm, MusicCreateForm
from music.utils import search
from users.models import CustomUser


def songsPage(request):
    '''Songs page view'''
    songs = search(request)
    new_song_for_player = Music.objects.filter(
        published=True).order_by('-created').first()
    context = {'songs': songs, 'player': new_song_for_player}

    return render(request, 'music/songs.html', context)


def singleSongPage(request, slug, pk):
    '''Single song page view'''
    song = Music.objects.get(slug=slug, pk=pk)
    song.page_view += 1
    song.save()
    form = MusicCommentForm()

    if request.method == 'POST':
        form = MusicCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.music = song
            comment.owner = request.user
            comment.active = True
            comment.save()

            messages.success(request, 'Successfully Submitted.')
            return redirect('single-song', slug=song.slug, pk=song.id)

    music_comments_count = song.musiccomment_set.filter(active=True).count()
    print(song.artist.username)
    context = {
        'song': song,
        'player': song,
        'form': form,
        'comments_count': music_comments_count
    }
    return render(request, 'music/single-song.html', context)


def downloadTrack(request, track_id):
    track = get_object_or_404(Music, id=track_id)
    track_path = track.song.path

    if os.path.exists(track_path):
        return FileResponse(open(track_path, 'rb'), as_attachment=True)
    else:
        return HttpResponseNotFound('Track not found')


@login_required
def songCreateAndEdit(request, slug=None, pk=None):
    user = request.user
    is_edit = False
    instance_song = None

    if pk is not None:
        instance_song = get_object_or_404(Music, slug=slug, pk=pk)
        is_edit = True
        print(f'first {slug}')

    form = MusicCreateForm(request.POST or None,
                           files=request.FILES or None,
                           instance=instance_song)

    if request.method == 'POST':
        if form.is_valid():
            try:
                song = form.save(commit=False)
                if not is_edit:
                    song.slug = (song.title + str(user.id) +
                                 str(Music.objects.all().count() + 1))
                    song.published = True
                    song.artist = user
                song.save()
                form.save_m2m()
                return redirect('single-song', slug=song.slug, pk=song.pk)
            except Exception as e:
                messages.error(request, (f'An error '
                                         f'occurred during registration: {e}'))
        else:
            messages.error(request, ('Form is not valid. '
                                     'Please correct the errors.'))

    context = {
        'form': form,
        'is_edit': is_edit,
        'song': instance_song,
    }
    return render(request, 'music/song-create.html', context)


def songDelete(request, slug, pk):
    if request.method == 'POST':
        user = CustomUser.objects.get(username=request.user.username)
        song = Music.objects.get(slug=slug, id=pk)
        song.delete()
        return redirect('single-artist', slug=user.slug, pk=user.id)

    song = Music.objects.get(slug=slug, pk=pk)
    return render(request, 'music/song-delete.html', {'song': song})

backend/templates/music/single-song.html
{% extends 'main.html' %}
{% load poll_extras %}
{% load static %}
{% block style %}
    .plyr__control--next, .plyr__control--prev, a[aria-label="Playlist"] {
        display: none;
    }
	.comments__img {
        height: auto;
        width: 50px !important;
        margin-right: 20px;
        border-radius: 12px;
    }
    .comments__autor {
        display: flex;
        align-items: center;
        padding-left: 0px;
    }
    #artists__link {
        margin-left: 10px;
    }
    #edit {
        background-color: #25a56a;
        padding: 10px;
        padding-left: 20px;
        padding-right: 20px;
        height: 50px;
        width: auto;
        border-radius: 12px;
        color: #fff;
        transition: 0.5s ease;
        transition-property: background-color;
        margin-left: 0px;
        margin-top: 10px;
    }
    #edit:hover {
        background-color: #222227;
    }
    .controls-link{
        width: 100%;
    }
{% endblock style %}
{% block title %} <title>{{song.title}} | JetSetRadio</title>{% endblock title %}
{% block content %}

<style>
    .comment__label{
        color: white;
    }
</style>

<main class="main">
    <div class="container-fluid">
        <div class="row row--grid">
            <div class="col-12">
                <ul class="breadcrumb">
                    <li class="breadcrumb__item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb__item"><a href="{% url 'songs' %}">Songs</a></li>
                </ul>
            </div>

            <div class="col-12">
                <div class="main__title main__title--page">
                    <h1>{{song.title}} - <a id="artists__link" href="{% url "single-artist" song.artist.slug song.artist.id%}">{{song.artist.username}}</a></h1>
                </div>
            </div>

            <div class="col-12">
                <div class="release">
                    <div class="release__content">
                        <div class="album__cover">
                            <img src="{{song.thumbnail.url}}" alt="">
                            <a data-link data-title="{{song.title}}" data-artist="{{song.artist.username}}" data-img="{{song.thumbnail.url}}" href="{{song.song.url}}" class="single-item__cover">
                                <img src="{{song.thumbnail.url}}" alt="">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2a3,3,0,0,0-3,3V19a3,3,0,0,0,6,0V5A3,3,0,0,0,16,2Zm1,17a1,1,0,0,1-2,0V5a1,1,0,0,1,2,0ZM8,2A3,3,0,0,0,5,5V19a3,3,0,0,0,6,0V5A3,3,0,0,0,8,2ZM9,19a1,1,0,0,1-2,0V5A1,1,0,0,1,9,5Z"/></svg>
                            </a>
                        </div>
                        <div class="release__stat">
                            <span><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.65,2.24a1,1,0,0,0-.8-.23l-13,2A1,1,0,0,0,7,5V15.35A3.45,3.45,0,0,0,5.5,15,3.5,3.5,0,1,0,9,18.5V10.86L20,9.17v4.18A3.45,3.45,0,0,0,18.5,13,3.5,3.5,0,1,0,22,16.5V3A1,1,0,0,0,21.65,2.24ZM5.5,20A1.5,1.5,0,1,1,7,18.5,1.5,1.5,0,0,1,5.5,20Zm13-2A1.5,1.5,0,1,1,20,16.5,1.5,1.5,0,0,1,18.5,18ZM20,7.14,9,8.83v-3L20,4.17Z"/></svg> {{song.song_duration}}</span>
                        </div>
                    </div>
                    <div class="controls-link">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'download-track' song.id %}" class="release__buy">Download - The highest quality</a>
                    {% else %}
                    <a href="{% url 'login' %}">Please log in to be able to download the music.</a>
                    {% endif %}
                    {% if user.is_authenticated and user == song.artist %}
                        <a id="edit" href="{% url "song-edit" song.slug song.id %}" class="sidebar__nav-link">Edit Song</a>
                        <a id="edit" href="{% url "song-delete" song.slug song.id %}" class="sidebar__nav-link">Delete Song</a>
                    {% endif %}
                    </div>
                </div>
            </div>

            <div class="col-12 col-lg-8">
                <div class="article">
                    <div class="article__content">
                        {% if song.lyrics %}
                        <h4>Lyric</h4>
                        <p>{{song.lyrics|linebreaksbr}}</p>
                        {% endif %}
                    </div>

                    <div class="comments">
                        <div class="comments__title">
                            <h4>Comments</h4>
                            <span>{{comments_count}}</span>
                        </div>

                        <ul class="comments__list">
                        {% for comment in song.musiccomment_set.all %}
                            {% if comment.active is True %}
                            <li class="comments__item">
                                <div class="comments__autor">
                                    <div>
                                        <img class="comments__img" src="{{comment.owner.picture.url}}">
                                    </div>
                                    <div>
                                        <span class="comments__name">{{comment.owner.username}}</span>
                                        <span class="comments__time">{{comment.created}}</span>
                                    </div>
                                </div>
                                <p class="comments__text">{{comment.body|charwrap}}</p>
                            </li>
                            {% endif %}
                        {% endfor %}
                        </ul>
                        
                        {% if request.user.is_authenticated %}
                        <form action="{% url 'single-song' song.slug song.id %}" method="post" class="comments__form">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="sign__group">
                                <label class="comment__label" for="sign__group">{{field.label}}</label>
                                {{field}}
                            </div>
                            {% endfor %}

                            <button type="submit" class="sign__btn">Send</button>
                        </form>
                        {% else %}
                            <p class="comments__text">Please log in to be able to leave a comment.</p>
                        {% endif %}
                    </div>
                </div>
            </div>
	
        </div>
    </div>
</main>
<script src="{% static 'js/form_show.js' %}"></script>
{% endblock content %}

backend/templates/music/song-create.html
{% extends 'main.html' %}
{% block style %}
	.plyr__control--next, .plyr__control--prev, a[aria-label="Playlist"] {
		display: none;
	}
    .sign__content {
        color: #fff;
    }
    #id_picture {
        width: 100%;
    }
    #current {
        display: block;
        width: 100%;
    }
    #now_picture {
        height: auto;
        width: 200px !important;
        margin-right: 20px;
        border-radius: 12px;
    }
    option {
        color: #25a56a;
        display: block;
        padding: 10px;
        margin: 5px 0;
        width: auto;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
        border: 2px solid #25a56a;
        transition: 0.5s ease;
        transition-property: color, background-color;
        text-align: center;
    }
    option:hover {
        background-color: #25a56a;
        color: #fff;
    }
    option:checked {
        color: #fff;
        background-color: #25a56a;
    }
    #id_genres {
        padding: 0;
        width: 100%;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        cursor: pointer;
        font-size: 16px;
        padding: 2px 10px;
        width: 100%;
        height: 9.6em;
    }
    #id_thumbnail, #id_song {
        padding-top: 6px;
        width: 100%;
    }
    #delete-modal {
        display: none;
        position: fixed;
        top: 350px;
        border: 2px solid #25a56a;
        z-index: 2;
    }
    .modal-content button {
        color: #25a56a;
    }
    .modal-content button:hover {
        color: #fff;
    }
    #confirm-delete {
        margin-right: 50px;
    }

{% endblock style %}
{% block title %} <title>Create Song | JetSetRadio</title>{% endblock title %}
{% block content %}
<!-- main content -->
<main class="main">
    <div class="container-fluid">
        <div class="row row--grid">

            {% if is_edit %}
            <div class="col-12">
                <div class="sign">
                    <div class="sign__content">
                        <form method="POST" action="{% url "song-edit" song.slug song.id %}" enctype="multipart/form-data" class="sign__form">
                            {% csrf_token %}
                            {% for field in form %}
                            {% if field.name == 'thumbnail' %}
                            <div class="sign__group">
                                <label class="breadcrumb__item">{{ field.label }}</label>
                                <br><label class="breadcrumb__item" id="current">Now User's Pciture:</label>
                                <div class="sign__group">
                                    <img src="{{ song.thumbnail.url }}" id="now_picture" alt="Image">
                                </div>

                                {{field}}

                                {% for error in field.errors %}
                                <p style="color: red;">{{error}}</p>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="sign__group">
                                <label class="breadcrumb__item">{{ field.label }}</label>
                                {{field}}

                                {% for error in field.errors %}
                                <p style="color: red;">{{error}}</p>
                                {% endfor %}
                            </div>
                            {% endif %}
                            {% endfor %}
                            <button class="sign__btn" type="submit">Edit Song</button>
                            <!-- Модальное окно для подтверждения удаления 
                            <div id="delete-modal" class="modal">
                                <div class="modal-content">
                                    <p>Вы уверены, что хотите удалить эту запись?</p>
                                    <button type="button" id="confirm-delete">Да</button>
                                    <button type="button" id="cancel-delete">Отмена</button>
                                </div>
                            </div>-->
                        </form>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="col-12">
                <div class="sign">
                    <div class="sign__content">
                        <form method="POST" action="{% url "song-create" %}" enctype="multipart/form-data" class="sign__form">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="sign__group">
                                <label class="breadcrumb__item">{{ field.label }}</label>
                                {{field}}

                                {% for error in field.errors %}
                                <p style="color: red;">{{error}}</p>
                                {% endfor %}
                            </div>
                            {% endfor %}
                            <button class="sign__btn" type="submit">Create Song</button>
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</main>
<!-- end main content -->
{% endblock content %}

backend/templates/music/song-delete.html
{% extends 'main.html' %}
{% block style %}
	.plyr__control--next, .plyr__control--prev, a[aria-label="Playlist"] {
		display: none;
	}
    .sign__content {
        color: #fff;
    }
    #id_picture {
        width: 100%;
    }
    #current {
        display: block;
        width: 100%;
    }
    #now_picture {
        height: auto;
        width: 200px !important;
        margin-right: 20px;
        border-radius: 12px;
    }
    option {
        color: #25a56a;
        display: block;
        padding: 10px;
        margin: 5px 0;
        width: auto;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        border-radius: 5px;
        border: 2px solid #25a56a;
        transition: 0.5s ease;
        transition-property: color, background-color;
        text-align: center;
    }
    option:hover {
        background-color: #25a56a;
        color: #fff;
    }
    option:checked {
        color: #fff;
        background-color: #25a56a;
    }
    #id_genres {
        padding: 0;
        width: 100%;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        cursor: pointer;
        font-size: 16px;
        padding: 2px 10px;
        width: 100%;
        height: 9.6em;
    }
    #id_thumbnail, #id_song {
        padding-top: 6px;
        width: 100%;
    }
    #delete-modal {
        border: 2px solid #25a56a;
        color: #fff;
    }
    .modal-content button, #cancel, #cancel:visited {
        color: #25a56a;
    }
    .modal-content button:hover, #cancel {
        color: #fff;
    }
    #confirm-delete {
        margin-right: 50px;
    }
    #cancel:visited:hover {
        color: #fff;
    }

{% endblock style %}
{% block title %} <title>Delete Song | JetSetRadio</title>{% endblock title %}
{% block content %}
<!-- main content -->
<main class="main">
    <div class="container-fluid">
        <div class="row row--grid">
            <div class="col-12">
            <form id="delete-form" action="{% url "song-delete" song.slug song.id %}" method="post">
                {% csrf_token %}
                <div id="delete-modal" class="modal">
                    <div class="modal-content">
                        <p>Вы уверены, что хотите удалить эту запись?</p>
                        <button type="submit" id="confirm-delete">Да</button>
                        <button type="button" id="cancel-delete">
                            <a id="cancel" href="{% url "single-song" song.slug song.id %}">
                                Отмена
                            <a/>
                        </button>
                    </div>
                </div>
                </form> 
            </div>
        </div>
    </div>
</main>
<!-- end main content -->
{% endblock content %}

backend/templates/music/songs.html
{% extends 'main.html' %}
{% block title %} <title>Songs | JetSetRadio</title>{% endblock title %}
{% block content %}
<!-- main content -->
<main class="main">
    <div class="container-fluid">
        <div class="row row--grid">
            <div class="col-12">
                <ul class="breadcrumb">
                    <li class="breadcrumb__item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="breadcrumb__item breadcrumb__item--active">Songs</li>
                </ul>
            </div>

            <div class="col-12">
                <div class="main__title main__title--page">
                    <h1>All Songs</h1>
                </div>
            </div>
        </div>

        <div class="row row--grid">
            <div class="col-12">
                <div class="main__filter">
                    <form method="get" action="{% url 'songs' %}" class="main__filter-search">
                        <input type="text" placeholder="Search in songs..." name="query">
                        <button type="submit"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M21.71,20.29,18,16.61A9,9,0,1,0,16.61,18l3.68,3.68a1,1,0,0,0,1.42,0A1,1,0,0,0,21.71,20.29ZM11,18a7,7,0,1,1,7-7A7,7,0,0,1,11,18Z"/></svg></button>
                    </form>
                </div>
                
                <div class="row row--grid">

                    {% for song in songs %}
                    <div class="col-6 col-sm-4 col-lg-2">
                        <div class="album">
                            <div class="album__cover">
                                <img src="{{song.thumbnail.url}}" alt="">
                                <a data-link data-title="{{song.title}}" data-artist="{{song.artist.username}}" data-img="{{song.thumbnail.url}}" href="{{song.song.url}}" class="single-item__cover">
                                    <img src="{{song.thumbnail.url}}" alt="">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M18.54,9,8.88,3.46a3.42,3.42,0,0,0-5.13,3V17.58A3.42,3.42,0,0,0,7.17,21a3.43,3.43,0,0,0,1.71-.46L18.54,15a3.42,3.42,0,0,0,0-5.92Zm-1,4.19L7.88,18.81a1.44,1.44,0,0,1-1.42,0,1.42,1.42,0,0,1-.71-1.23V6.42a1.42,1.42,0,0,1,.71-1.23A1.51,1.51,0,0,1,7.17,5a1.54,1.54,0,0,1,.71.19l9.66,5.58a1.42,1.42,0,0,1,0,2.46Z"/></svg>
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="M16,2a3,3,0,0,0-3,3V19a3,3,0,0,0,6,0V5A3,3,0,0,0,16,2Zm1,17a1,1,0,0,1-2,0V5a1,1,0,0,1,2,0ZM8,2A3,3,0,0,0,5,5V19a3,3,0,0,0,6,0V5A3,3,0,0,0,8,2ZM9,19a1,1,0,0,1-2,0V5A1,1,0,0,1,9,5Z"/></svg>
                                </a>
                            </div>
                            <div class="album__title">
                                <h3><a href="{% url 'single-song' song.slug song.id %}">{{song.title}}</a></h3>
                                <span>
                                    <a href="{% url 'single-artist' song.artist.slug song.artist.id %}">{{song.artist.username}}</a>
                                </span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

            </div>
        </div>
    </div>
</main>
{% endblock content %}